server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
logging:
  config: classpath:logback-spring.xml

spring:
  profiles:
    active:
      - D
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    generate-ddl: false
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/INT_DB?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&&allowPublicKeyRetrieval=true&&validationQuery="select 1"
    username: INT_ADMIN
    password: aa12345^
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 0b7da71d12ae9a16a2e0
            clientSecret: 93e76a3cf476cd4715658d693517404f8cbb828c

---
spring:
  profiles:
    - D
  datasource:
    url: jdbc:mysql://18.217.155.120:3306/INT_DB?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&&allowPublicKeyRetrieval=true&&validationQuery="select 1"
    username: INT_ADMIN
    password: aa12345^
    driver-class-name: com.mysql.cj.jdbc.Driver

