server:
  port: 8080

spring:
  profiles:
    active:
      - L
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://18.217.155.120:3306/INT_DB?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&&allowPublicKeyRetrieval=true&&validationQuery="select 1"
    username: INT_ADMIN
    password: aa12345^
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 0b7da71d12ae9a16a2e0
            clientSecret: 93e76a3cf476cd4715658d693517404f8cbb828c
logging:
  config: classpath:logback-spring.xml